version: 2.1
jobs:
  run:
    docker:
      - image: circleci/python:3.7.0
        steps:
          - checkout
          -- run:
                name: install dependency
                command: | 
                  echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
                  pip install --user -r requirements.txt