"""updates

Revision ID: 4bd73dfac3ba
Revises: b8f3058949da
Create Date: 2023-11-06 18:18:03.857501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd73dfac3ba'
down_revision = 'b8f3058949da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('updated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('updated')
    # ### end Alembic commands ###
