"""masters

Revision ID: b8f3058949da
Revises: 6aeb061fa31e
Create Date: 2023-11-06 16:41:22.655682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f3058949da'
down_revision = '6aeb061fa31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos', sa.String(length=4), nullable=True),
    sa.Column('player', sa.String(length=255), nullable=True),
    sa.Column('r1', sa.String(length=4), nullable=True),
    sa.Column('r2', sa.String(length=4), nullable=True),
    sa.Column('r3', sa.String(length=4), nullable=True),
    sa.Column('r4', sa.String(length=4), nullable=True),
    sa.Column('to_par', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('masters')
    # ### end Alembic commands ###
