"""Draft

Revision ID: efec640f5d93
Revises: 4bd73dfac3ba
Create Date: 2023-11-08 17:04:28.977729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efec640f5d93'
down_revision = '4bd73dfac3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tier1', sa.String(length=64), nullable=True),
    sa.Column('tier2', sa.String(length=64), nullable=True),
    sa.Column('tier3', sa.String(length=64), nullable=True),
    sa.Column('tier4', sa.String(length=64), nullable=True),
    sa.Column('tier5', sa.String(length=64), nullable=True),
    sa.Column('tier6', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft')
    # ### end Alembic commands ###
