"""Modify to_par column type

Revision ID: f0c3516d8343
Revises: 2d0ff7b95630
Create Date: 2023-12-07 15:54:59.398567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c3516d8343'
down_revision = '2d0ff7b95630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masters', schema=None) as batch_op:
        batch_op.alter_column('to_par',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masters', schema=None) as batch_op:
        batch_op.alter_column('to_par',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###
