"""playerid

Revision ID: fb2be286f1d4
Revises: 18c090f5ae45
Create Date: 2023-12-29 11:54:36.290118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2be286f1d4'
down_revision = '18c090f5ae45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('t1_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('t2_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('t3_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('t4_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('t5_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('t6_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('masters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playerId', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masters', schema=None) as batch_op:
        batch_op.drop_column('playerId')

    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.drop_column('t6_id')
        batch_op.drop_column('t5_id')
        batch_op.drop_column('t4_id')
        batch_op.drop_column('t3_id')
        batch_op.drop_column('t2_id')
        batch_op.drop_column('t1_id')

    # ### end Alembic commands ###
